name: app_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  csv: ^6.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/Images/icon.png"
  image_path: "assets/Images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/recettes.csv
    - assets/Images/
    - assets/Images/Pizza.jpg
    - assets/Images/Ratatouille.jpg
    - assets/Images/Porc_caramelise.jpg
    - assets/Images/Hamburger_frites.jpg
    - assets/Images/quiche.jpg
    - assets/Images/cordon_bleu.jpg
    - assets/Images/Couscous_perle.jpg
    - assets/Images/curry_katsu.jpg
    - assets/Images/pates_pesto.jpg
    - assets/Images/pates_saucisseitalienne.jpg
    - assets/Images/chicken_finger.jpg
    - assets/Images/Moussaka.jpg
    - assets/Images/risotto_chorizo.jpg
    - assets/Images/samossa.jpg
    - assets/Images/curry_vert.jpg
    - assets/Images/pates_ail.jpg
    - assets/Images/pain_saucisse.jpg
    - assets/Images/pates_vodka.jpg
